build.conf: Add missing dependency on apr-util to svnserve executable; otherwise CMake will not build this target with shared ra-svn and fail due to undefined reference to `apr_thread_pool_threshold_set'.
* build.conf
  (svnserve): Add aprutil to 'libs' field.


git-svn-id: https://svn.apache.org/repos/asf/subversion/trunk@1920468 13f79535-47bb-0310-9956-ffa450edef68