Follow-up to r1667692:
Blind attempt to fix a build failure with Windows compilers:
conflict-callbacks.c(746): error C2466: cannot allocate an array of
constant size 0

* subversion/svn/conflict-callbacks.c
  (handle_text_conflict): Allocate options dynamically.


git-svn-id: https://svn.apache.org/repos/asf/subversion/trunk@1667699 13f79535-47bb-0310-9956-ffa450edef68