* subversion/libsvn_wc/questions.c (svn_wc_check_wc): Return error if path does not exist, as doc string has always promised.
* subversion/libsvn_wc/entries.c (svn_wc_entry): Use correct path in
error if dir is not a working copy.

This fixes a bug reported by Daniel Stenberg <daniel@haxx.se>.  It
didn't live long enough to get an issue, so here is his original
report:

   From: Daniel Stenberg <daniel@haxx.se>
   Subject:  interesting error when server is being silly
   To: dev@subversion.tigris.org
   Date: Thu, 24 Jan 2002 15:46:53 +0100 (MET)
   
   [...]
   $ svn st -u

   svn_error: #21022 : <Obstructed update>
     svn_wc_entry: ./subversion/bindings/swig/python/fstest.py \
     is not a working copy directory
   
   This is a very odd error, since:
   
   $ ls -l ./subversion/bindings/swig/python/
   ls: ./subversion/bindings/swig/python/: No such file or directory
   [...]


git-svn-id: https://svn.apache.org/repos/asf/subversion/trunk@841118 13f79535-47bb-0310-9956-ffa450edef68