Fix byte vs. string confusion in mailer.py DiffGenerator class.
Fixes "AttributeError: 'str' object has no attribute 'decode'"
which could be triggered by the mailer.py test suite.

* tools/hook-scripts/mailer/mailer.py
  (DiffGenerator): Consumers of this class expect the base_path to
   be a byte string. Store the byte string instead of a local copy
   which has already been converted to a string object.


git-svn-id: https://svn.apache.org/repos/asf/subversion/trunk@1885784 13f79535-47bb-0310-9956-ffa450edef68