Fix issue #2488, mis-reporting of failed repository creation (e.g. because the path to svnadmin is invalid), which was often reported as:
  IOError: [Errno 2] No such file or directory:
  'svn-test-work/local_tmp/repos/conf/svnserve.conf'


* subversion/tests/cmdline/svntest/main.py
  (SVNRepositoryCreateFailure): New exception raised if we're unable
   to create a repository.

  (create_repos): Raise SVNRepositoryCreateFailure if the repository
   creation writes anything to stderr.


Patch by: Tobias Schäfer <tobiasschaefer@gmx.de>
(Tweaked by me.)


git-svn-id: https://svn.apache.org/repos/asf/subversion/trunk@859223 13f79535-47bb-0310-9956-ffa450edef68