Fix an TypeError exception in 'release.py create-tag'.
Regular expression matching failed due to lack of an explicit encoding
for files modified during the post-release housekeeping step.

The exception was observed with Python 3.7.7 and looked as follows:

INFO:root:Bumping version numbers on the branch
Traceback (most recent call last):
  File "/home/stsp/svn/svn-trunk/tools/dist/release.py", line 1916, in <module>
    main()
  File "/home/stsp/svn/svn-trunk/tools/dist/release.py", line 1912, in main
    args.func(args)
  File "/home/stsp/svn/svn-trunk/tools/dist/release.py", line 1134, in create_tag_and_bump_versions
    bump_versions_on_branch(args)
  File "/home/stsp/svn/svn-trunk/tools/dist/release.py", line 1108, in bump_versions_on_branch
    str(args.version.patch), str(new_version.patch))
  File "/home/stsp/svn/svn-trunk/tools/dist/release.py", line 1078, in replace_in_place
    replacement = re.sub(pattern, repl, line)
  File "/usr/local/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object

* tools/dist/release.py
  (bump_versions_on_branch): Create temporary file handles with an explicit
   encoding argument (assume UTF-8).


git-svn-id: https://svn.apache.org/repos/asf/subversion/trunk@1877953 13f79535-47bb-0310-9956-ffa450edef68