Make our swig proxy wrapper generator write to intermediate temporary files instead of writing to the result files directly.
Works around errors seen on some platforms, e.g. Suse Linux, such as:
/usr/src/packages/BUILD/subversion-1.3.x/subversion/bindings/swig/core.i:613: \
  Error: Unable to find 'svn_auth_h.swg'

* build/generator/swig/header_wrappers.py
  (Generator._write_nodefault_calls): Open a temporary file for other
    methods to write to, and upon success copy the result to the actual
    output file. We could use a more efficient solution (rename the
    temporary file) if we raised the minimum Python version required to
    build Subversion to 2.6. I'd say the only person who would not have
    a problem with this is Arfrever :)

Patch by: OpenSUSE packagers
(but I've essentially rewritten it by adding proper tempfile handling)


git-svn-id: https://svn.apache.org/repos/asf/subversion/trunk@878361 13f79535-47bb-0310-9956-ffa450edef68