Following up on r1700215, unbreak the test runner's compabitility mode.
For instance, make check SERVER_MINOR_VERSION=8 used to error out
like this:

  Traceback (most recent call last):
    File "./build/run_tests.py", line 789, in <module>
      main()
    File "./build/run_tests.py", line 782, in main
      failed = th.run(args[2:])
    File "./build/run_tests.py", line 322, in run
      self._init_c_tests()
    File "./build/run_tests.py", line 196, in _init_c_tests
      self.opts.server_minor_version)
  TypeError: cannot concatenate 'str' and 'int' objects

* build/run_tests.py
  (TestHarness._init_c_tests): Use %d format for the minor version value,
   as we already do in _init_py_tests().

* win-tests.py:
  (): Convert the minor version value to integer, as we'll then be passing
   it to TestHarness.__init__() that expects an int.


git-svn-id: https://svn.apache.org/repos/asf/subversion/trunk@1706375 13f79535-47bb-0310-9956-ffa450edef68