Python bindings: Hopefully fix the "undefined reference to SWIG_ConvertPtr" errors people have been reporting. I am puzzled, because I don't understand how the existing code ever worked with swig 1.3.21 in the past, but at the same time, I know it did.
* subversion/bindings/swig/python/libsvn_swig_py/swigutil_py.h:
    Make sure to #define SWIG_ConvertPtr SWIG_Python_ConvertPtr.


git-svn-id: https://svn.apache.org/repos/asf/subversion/trunk@852625 13f79535-47bb-0310-9956-ffa450edef68