Make sure msgstr is not None before do iteration.
Obvious fix.

* tools/dev/po-merge.py
  Since parse_translation maybe return (comments, None, None, None),
  we should not do iteration without check msgstr is not None. Otherwise,
  we may encounter the following TypeError:

    Traceback (most recent call last):
      File "../../../../trunk/tools/dev/po-merge.py", line 196, in <module>
        main(sys.argv)
      File "../../../../trunk/tools/dev/po-merge.py", line 181, in main
        for m in msgstr:
    TypeError: 'NoneType' object is not iterable


git-svn-id: https://svn.apache.org/repos/asf/subversion/trunk@1498947 13f79535-47bb-0310-9956-ffa450edef68